### ISSUE TITLE
PrintToXmlString produces corrupted string output

### ISSUE THREAD

**Issue by jayeshkm** [tmarthal/pb2xml#2]
When using PrintToXmlString  to convert protobuf to XML format and print it, it prints junk characters.
After looking deep into the implementation, I could see that the usage of "allocate_node" method from rapidxml was not correct. The api does not hold ownership of the node name and node value strings passed to it, instead it just holds the pointer to it. This causes corruption as it points to a variable in stack.
The correct usage is to allocate strings using the method "doc->allocate_string" and use it as arguments to allocate_node. After making this change the output looks good.

**Comment by tmarthal** [comment]
I merged the CR. Should be good. Future xml <-> protobufers thank you.
