### ISSUE TITLE
added all file in my code but it is not compiling 

### ISSUE THREAD

**Issue by puneetsahu** [tmarthal/pb2xml#5]
Added all file in my code but it is not compiling.

Get_Data.cc:(.text+0x796): undefined reference to `google::protobuf::XmlFormat::PrintToXmlString(google::protobuf::Message const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'

What can be done ?

Regards,
Puneet

**Comment by tmarthal** [comment]
The Protobuf library changed their API. Feel free to fix the print statement and submit a PR.
